name: PullRequest-Checks
on:
  pull_request:
    branches:
      - develop
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - name: List files in the workspace
      run: |
        ls ${{ github.workspace }}
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: List files in the workspace
      run: |
        ls ${{ github.workspace }}
    - name: Run npm install
      run: npm install
    - name: Run npm lint
      run: npm lint
    - name: Run npm install
      run: npm install
    - name: Run npm test
      run: npm test
